version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: news-portal-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: newsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d newsdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: